### ISSUE TITLE
Error: Unexpected token You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by brentdodell** [digiaonline/react-foundation#46] opened 2017-09-01 21:32 UTC
I get the following error when trying to transpile with babel through webpacker. My guess is I'm missing a babel plugin, but I haven't been able to figure out which one. Has anyone else experienced this and found a fix?

Thanks!

<img width="1015" alt="screen shot 2017-09-01 at 4 10 02 pm" src="https://user-images.githubusercontent.com/9657923/29988479-29fd14aa-8f33-11e7-98cd-eaeacc4617c4.png">

**Comment by crisu83** [comment] 2017-09-02 09:27
I would strongly recommend using the configurations that you get when you create your project using [Create React App](https://github.com/facebookincubator/create-react-app).

Closing this issue because it's most likely caused by a faulty Webpack configuration.

**Closed by crisu83** 2017-09-02 09:27 UTC
Labels: question
